# Generated by Django 5.0.4 on 2026-05-02 00:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_location', models.CharField(max_length=500)),
                ('current_lat', models.FloatField()),
                ('current_lng', models.FloatField()),
                ('pickup_location', models.CharField(max_length=500)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('dropoff_location', models.CharField(max_length=500)),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lng', models.FloatField()),
                ('current_cycle_used_hours', models.FloatField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_distance_miles', models.FloatField()),
                ('total_driving_hours', models.FloatField()),
                ('total_days', models.IntegerField()),
                ('route_geometry', models.JSONField()),
                ('stops', models.JSONField()),
                ('eld_segments', models.JSONField()),
                ('daily_logs', models.JSONField()),
                ('cache_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('trip_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='trips.triprequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
